### ISSUE TITLE
Fix possible confusion with unsaved results and the "Explore in Iodide" button 

### ISSUE THREAD

**Issue by felixlawrence** [iodide-project/redash-iodide#3]
Yesterday I got confused because I didn't realise that results needed to be saved in Redash before they can be accessed by Iodide. This was a particular problem because I was editing someone else's query, so there wasn't even a "Save" button visible in the Redash interface to give me a hint that this concept/functionality exists. I expected Iodide to work with the results that were visible in Redash at that point in time.

Suggestions:
* When unsaved data is visible in Redash, change "Explore in Iodide" to "Save and Explore in Iodide" (change both the text and the action)
* When unsaved data is visible in Redash and the user doesn't have permission to save it, disable the "Save and Explore in Iodide" (so that the user can see that the Iodide functionality is present but unavailable) - ideally with a further message in a tooltip or elsewhere explaining that the user should fork the query first.
* When a user loads someone else's saved query, if they don't edit and execute the query then the "Explore in Iodide" button should still be enabled as it is now.

**Comment by openjck** [comment]
Thanks, Felix. I'll look into this.
